# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ecriso4217}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Enrique Comba Riepenhausen"]
  s.date = %q{2009-10-08}
  s.description = %q{When dealing with currencies in code you don't need to roll up your
                         own interpretation of a currency. Now you can just use the ISO 4217
                         gem to work with them.}
  s.email = %q{ecomba@nexwerk.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "lib/iso4217.rb",
     "lib/iso4217/currencies.rb",
     "lib/iso4217/currency.rb",
     "lib/iso4217/iso4217.rb",
     "spec/currency_spec.rb",
     "spec/iso4217_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ecomba/ecriso4217}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Currencies as described by the ISO 4217 Standard}
  s.test_files = [
    "spec/currency_spec.rb",
     "spec/iso4217_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
